-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.company
(
    id integer NOT NULL,
    user_id integer NOT NULL,
    company_name character varying(200) NOT NULL,
    website character varying(100) NOT NULL,
    company_email character varying(100),
    phone character varying(20),
    is_verify boolean,
    verification_code character varying(100),
    company_logo character varying(100),
    company_city integer,
    PRIMARY KEY (id)
);

CREATE TABLE public.company_sector_positions
(
    id integer NOT NULL,
    company_sector_id integer NOT NULL,
    position_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.company_sectors
(
    id integer NOT NULL,
    company_id integer NOT NULL,
    sector_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.company_users
(
    id integer NOT NULL,
    company_id integer NOT NULL,
    user_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.countrie_citys
(
    id integer NOT NULL,
    countrie_id integer NOT NULL,
    city_name character varying(100) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.countries
(
    id integer NOT NULL,
    countrie_name character varying(40) NOT NULL,
    countrie_flag character varying(200),
    PRIMARY KEY (id)
);

CREATE TABLE public.education_institues
(
    id integer NOT NULL,
    education_type_id integer NOT NULL,
    institue_name character varying(100) NOT NULL,
    institue_info text,
    institue_logo character varying,
    institue_website character varying(200),
    institue_city integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.education_types
(
    id integer NOT NULL,
    education_type_name character varying(100) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.job_position_application_states
(
    id integer NOT NULL,
    state_name character varying(30) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.job_position_applications
(
    id integer NOT NULL,
    job_position_id integer NOT NULL,
    person_id integer NOT NULL,
    person_cv_id integer NOT NULL,
    application_date time with time zone NOT NULL,
    application_state integer NOT NULL,
    is_accepted boolean NOT NULL,
    application_visibility boolean NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.job_position_professions
(
    id integer NOT NULL,
    job_position_id integer NOT NULL,
    position_profession_id integer NOT NULL,
    profession_description text,
    PRIMARY KEY (id)
);

CREATE TABLE public.job_position_views
(
    id bigint NOT NULL,
    job_position_id integer NOT NULL,
    user_id integer NOT NULL,
    view_time time with time zone NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.job_positions
(
    id integer NOT NULL,
    company_sctor_position_id integer NOT NULL,
    company_id integer NOT NULL,
    job_position_status boolean NOT NULL,
    job_position_listing_date time with time zone NOT NULL,
    job_application_start time with time zone NOT NULL,
    job_application_end time with time zone NOT NULL,
    referance_title character varying(250) NOT NULL,
    referance_content text NOT NULL,
    company_atendance_person integer NOT NULL,
    work_type_id integer NOT NULL,
    worker_type_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.language_levels
(
    id integer NOT NULL,
    level_name character varying(50) NOT NULL,
    level_value integer,
    PRIMARY KEY (id)
);

CREATE TABLE public.languages
(
    id integer NOT NULL,
    language_name character varying(100) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.news
(
    id integer NOT NULL,
    system_user_id integer NOT NULL,
    status boolean NOT NULL,
    showcase_visibility boolean NOT NULL,
    news_caption character varying(250) NOT NULL,
    news_content text NOT NULL,
    news_photo character varying(200) NOT NULL,
    news_view_start_date time with time zone NOT NULL,
    news_view_end_date time with time zone NOT NULL,
    news_raiting integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.news_sector_position_professions
(
    id integer NOT NULL,
    news_id integer NOT NULL,
    sector_position_profession_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.news_sector_positions
(
    id integer NOT NULL,
    news_id integer NOT NULL,
    sector_position_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.news_sectors
(
    id integer NOT NULL,
    news_id integer NOT NULL,
    sector_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.news_views
(
    id integer NOT NULL,
    news_id integer NOT NULL,
    user_id integer NOT NULL,
    view_time time with time zone NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.news_worker_types
(
    id integer NOT NULL,
    news_id integer NOT NULL,
    worker_type_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.person
(
    id integer NOT NULL,
    user_id integer NOT NULL,
    name character varying(50),
    surname character varying(30),
    national_identity character varying(11),
    date_of_birth time with time zone,
    is_verify boolean,
    verification_code character varying(100),
    phone character varying(20),
    PRIMARY KEY (id)
);

CREATE TABLE public.person_ceritificates
(
    id integer NOT NULL,
    person_id integer NOT NULL,
    certifica_name character varying(200) NOT NULL,
    certifica_info text,
    certifica_date time with time zone NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.person_certifica_documents
(
    id integer NOT NULL,
    person_certificates_id integer NOT NULL,
    certifica_name character varying(200) NOT NULL,
    certifica_file character varying(200) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.person_course_documents
(
    id integer NOT NULL,
    person_course_id integer NOT NULL,
    document_name character varying(100) NOT NULL,
    document_file character varying(200) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.person_courses
(
    id integer NOT NULL,
    person_id integer NOT NULL,
    course_name character varying(200) NOT NULL,
    course_info text,
    course_date time with time zone NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.person_cv
(
    id integer NOT NULL,
    person_id integer NOT NULL,
    cv_caption character varying(200) NOT NULL,
    sc_content text NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.person_cv_educations
(
    id integer NOT NULL,
    person_educations_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.person_cv_experiences
(
    id integer NOT NULL,
    person_cv_id integer NOT NULL,
    person_work_experiences_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.person_educations
(
    id integer NOT NULL,
    person_id integer NOT NULL,
    education_institues_id integer NOT NULL,
    education_info text,
    education_start_date time with time zone NOT NULL,
    education_end_date time with time zone NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.person_languages
(
    id integer NOT NULL,
    person_id integer NOT NULL,
    language_id integer NOT NULL,
    language_level_id integer NOT NULL,
    language_level_info text,
    PRIMARY KEY (id)
);

CREATE TABLE public.person_sector_positions
(
    id integer NOT NULL,
    person_sector_id integer NOT NULL,
    position_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.person_sector_professions
(
    id integer NOT NULL,
    person_sector_position_id integer NOT NULL,
    position_profession_id integer NOT NULL,
    person_profession_info text,
    PRIMARY KEY (id)
);

CREATE TABLE public.person_sectors
(
    id integer NOT NULL,
    person_id integer NOT NULL,
    sector_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.person_work_experiences
(
    id integer NOT NULL,
    person_id integer NOT NULL,
    person_sector_profession_id integer NOT NULL,
    company_id integer,
    other_company_info character varying(200),
    experiences_caption character varying(250),
    experiences_content text,
    experiences_start_date time with time zone,
    experiences_end_date time with time zone,
    PRIMARY KEY (id)
);

CREATE TABLE public.position_profession
(
    id integer NOT NULL,
    position_sector_id integer NOT NULL,
    profession_name character varying(50) NOT NULL,
    profession_description text,
    profession_avatar character varying(100),
    PRIMARY KEY (id)
);

CREATE TABLE public.positions
(
    id integer NOT NULL,
    sector_id integer NOT NULL,
    position_name character varying(50) NOT NULL,
    position_avatar character varying(100),
    PRIMARY KEY (id)
);

CREATE TABLE public.sector
(
    id integer NOT NULL,
    sector_name character varying(50) NOT NULL,
    sector_avatar character varying(100),
    PRIMARY KEY (id)
);

CREATE TABLE public.showcase_job_positions
(
    id integer NOT NULL,
    job_position_id integer NOT NULL,
    show_case_visibility boolean NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.showcase_sectors
(
    id integer NOT NULL,
    sector_id integer NOT NULL,
    showcase_visibility boolean NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.system_user
(
    id integer NOT NULL,
    userid integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public."user"
(
    id integer NOT NULL,
    email character varying(100) NOT NULL,
    password character varying(100) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.work_types
(
    id integer NOT NULL,
    work_type_name character varying(30) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.worker_types
(
    id integer NOT NULL,
    worker_type_name character varying(30) NOT NULL,
    PRIMARY KEY (id)
);
END;